name: ramirez
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - asttokens=3.0.1
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.2
  - cycler=0.12.1
  - debugpy=1.8.19
  - decorator=5.2.1
  - double-conversion=3.3.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - graphite2=1.3.14
  - harfbuzz=11.0.0
  - icu=75.1
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - joblib=1.5.3
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.8
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.84.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libpng=1.6.54
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mkl=2025.3.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numpy=1.24.3
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.0.3
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.3.1
  - pyside6=6.9.0
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.0
  - scikit-learn=1.3.0
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=17.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - check-shapes==1.1.1
      - cloudpickle==3.1.2
      - deprecated==1.3.1
      - dill==0.3.5.1
      - dm-tree==0.1.9
      - dropstackframe==0.1.1
      - flatbuffers==25.12.19
      - gast==0.4.0
      - google-auth==2.47.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gpflow==2.9.0
      - gpflux==0.4.3
      - greenlet==3.3.0
      - grpcio==1.74.0
      - h5py==3.15.1
      - idna==3.11
      - jax==0.4.38
      - jaxlib==0.4.38
      - keras==2.12.0
      - lark==1.3.1
      - libclang==18.1.1
      - llvmlite==0.46.0
      - markdown==3.10
      - markupsafe==3.0.3
      - ml-dtypes==0.5.4
      - multipledispatch==1.0.0
      - numba==0.63.1
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - shap==0.41.0
      - slicer==0.0.7
      - tabulate==0.9.0
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.2
      - tensorflow==2.12.1
      - tensorflow-estimator==2.12.0
      - tensorflow-intel==2.12.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorflow-probability==0.18.0
      - termcolor==3.3.0
      - tqdm==4.67.1
      - trieste==3.1.0
      - typing-extensions==4.5.0
      - urllib3==2.6.3
      - werkzeug==3.1.5
      - wrapt==1.14.2
prefix: C:\Users\Flo\anaconda3\envs\ramirez
